// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgjAOSR4qjouX3ycEYlsETJwr2Gq3Q8pc',
    appId: '1:846867357261:web:60c9f133b4c995b8fb8604',
    messagingSenderId: '846867357261',
    projectId: 'sp-taskflow',
    authDomain: 'sp-taskflow.firebaseapp.com',
    storageBucket: 'sp-taskflow.firebasestorage.app',
    measurementId: 'G-71ZC5QF4D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmp_ueonNlNnqhHO3gV1F6-mkw6qu4NT0',
    appId: '1:846867357261:android:cbba0256a83b6d35fb8604',
    messagingSenderId: '846867357261',
    projectId: 'sp-taskflow',
    storageBucket: 'sp-taskflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo8xBbxwQGKk0SENdg-btVLfgk3qjZC_s',
    appId: '1:846867357261:ios:d78ae181e663065bfb8604',
    messagingSenderId: '846867357261',
    projectId: 'sp-taskflow',
    storageBucket: 'sp-taskflow.firebasestorage.app',
    iosBundleId: 'com.sp.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo8xBbxwQGKk0SENdg-btVLfgk3qjZC_s',
    appId: '1:846867357261:ios:d78ae181e663065bfb8604',
    messagingSenderId: '846867357261',
    projectId: 'sp-taskflow',
    storageBucket: 'sp-taskflow.firebasestorage.app',
    iosBundleId: 'com.sp.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgjAOSR4qjouX3ycEYlsETJwr2Gq3Q8pc',
    appId: '1:846867357261:web:3828b2d40b5b6e77fb8604',
    messagingSenderId: '846867357261',
    projectId: 'sp-taskflow',
    authDomain: 'sp-taskflow.firebaseapp.com',
    storageBucket: 'sp-taskflow.firebasestorage.app',
    measurementId: 'G-5FKVJCN1HG',
  );
}
